name: Test Disco Sovenok
on: push
jobs:
  test-mod:
    runs-on: ubuntu-latest
    container:
      image: shcnik/es_mod_testing:v1
      env:
        SDL_AUDIODEVICE: dummy
        SDL_VIDEODEVICE: dummy
        MODNAME: disco_sovenok
      volumes:
        - ${{ github.workspace }}:/opt
