name: Test Disco Sovenok
on: push
jobs:
  test-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run test
        run: |
          docker build -f .test/Dockerfile . -t shcnik/estool;
          docker run shcnik/estool;
